import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from '../styles/Home.module.css'
import Link from "next/link"

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        
        <div className={styles.center}>
        <h6>Hi Girl🫦</h6>
        </div>

        <div className={styles.grid}>

          <Link href="/">
            <div className={styles.card}>
              <h2>Home <span>-&gt;</span></h2>
              <p>This Home Page</p>
            </div>
          </Link>

          <Link href="/about"> 
            <div className={styles.card}>
              <h2>About <span>-&gt;</span></h2>
              <p>about me!</p>
            </div>
          </Link>

          <Link href="/contect">
            <div className={styles.card}>
              <h2>Contact <span>-&gt;</span></h2>
              <p>Contact me</p>
            </div>
          </Link>

          <Link href="/page1">
            <div className={styles.card}>
              <h2>Page 1 <span>-&gt;</span></h2>
              <p>Page 1</p>
            </div>
          </Link>

          <Link href="/page2">
            <div className={styles.card}>
              <h2>Page 2 <span>-&gt;</span></h2>
              <p>Page 2</p>
            </div>
          </Link>

          <Link href="/page3">
            <div className={styles.card}>
              <h2>Page 3 <span>-&gt;</span></h2>
              <p>Page 3</p>
            </div>
          </Link>

          <Link href="/page4">
            <div className={styles.card}>
              <h2>Page 4 <span>-&gt;</span></h2>
              <p>Page 4</p>
            </div>
          </Link>

        </div>
      </main>
    </>
  );
}
